name: Release
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Instalar as dependencias
        run: npm install
      - name: Executar testes de unidade
        run: npm run test:unit
