name: Release
on:
  push:
    branches: [master]
  workflow_dispatch:
env:
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Instalar as dependencias
        run: npm install
      - name: Executar testes de unidade
        run: npm run test:unit
      - name: Instalação do Heroku
        run: npm install -g heroku
      - name: Login no Heroku
        run: heroku authorizations:create
      - name: Enviar para o servidor da Heroku
        run: git push heroku master
